### ISSUE TITLE
I am not able to enter decimal places in Amount field.

### ISSUE THREAD

**Issue by yoonp** [dutch-pay/dutch-pay.github.io#1]
I am not able to enter decimal places in Amount field. It shows a red flag without further details. It would be nicer to explain to users why such values (eg. $35.63) is not allowed.

![image](https://user-images.githubusercontent.com/22037745/99172249-de0ab580-26d7-11eb-9169-2c2784f8d061.png)

**Comment by aria-grande** [comment]
Thanks for creating an issue @yoonp :D

**Comment by aria-grande** [comment]
https://github.com/dutch-pay/dutch-pay.github.io/commit/a20f430685d664f4e00130b3f0aa36a7b1224a65
